# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        my_min_up_scale_filter:
            filters:
                
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [ 300, 300 ]
                    mode: outbound
                    allow_upscale: true
                    upscale:
                        min: [300,300]

    
        squared_thumbnail_small:
            filters:
               thumbnail:
                    size: [ 200, 200 ]
                    mode: outbound
                    allow_upscale: true
                    upscale:
                        min: [200,200]

